"""Batch processing and aggregation across multiple audio files."""

from __future__ import annotations

from collections import Counter
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from .config import THRESHOLDS, Thresholds
from .insight import generate_insight
from .insight.llm import LLMUnavailable, complete_json, model_label
from .models import AudioReport, BatchReport, IssueType
from .pipeline import analyze_file

AUDIO_EXTENSIONS = {".wav", ".mp3", ".m4a", ".flac", ".aac", ".ogg", ".opus", ".wma"}


def find_audio_files(directory: Path) -> list[Path]:
    return sorted(
        p for p in directory.rglob("*") if p.is_file() and p.suffix.lower() in AUDIO_EXTENSIONS
    )


def _mean(values: list[float]) -> float | None:
    return round(sum(values) / len(values), 3) if values else None


def analyze_directory(
    directory: Path,
    *,
    use_llm: bool = True,
    max_workers: int = 4,
    config: Thresholds = THRESHOLDS,
) -> BatchReport:
    """Analyse every audio file under ``directory`` and aggregate the results.

    Files are processed concurrently (ffmpeg is the bottleneck and releases the GIL via
    subprocess), with per-file LLM insight attached. Aggregates surface fleet-level signals:
    averages, which files clip or run quiet, and the most common issues.
    """

    files = find_audio_files(directory)

    def _process(path: Path) -> AudioReport:
        report = analyze_file(path, config=config)
        report.insight = generate_insight(report, use_llm=use_llm)
        return report

    with ThreadPoolExecutor(max_workers=max_workers) as pool:
        reports = list(pool.map(_process, files))

    counts: Counter[str] = Counter()
    for report in reports:
        for issue in report.issues:
            counts[issue.type.value] += 1

    durations = [r.duration_seconds for r in reports if r.duration_seconds]
    ratios = [r.audio_quality.silence_ratio for r in reports if not r.error]
    clipping = [r.file_name for r in reports if r.audio_quality.clipping_detected]
    low_volume = [
        r.file_name
        for r in reports
        if any(i.type is IssueType.low_volume for i in r.issues)
    ]

    batch = BatchReport(
        file_count=len(reports),
        reports=reports,
        issue_counts=dict(counts),
        average_duration_seconds=_mean(durations),
        average_silence_ratio=_mean(ratios),
        files_with_clipping=clipping,
        files_with_low_volume=low_volume,
        top_issues=[issue for issue, _ in counts.most_common(3)],
    )
    batch.aggregate_summary = _aggregate_summary(batch, use_llm=use_llm)
    return batch


_AGG_SYSTEM = (
    "You are an audio-quality analyst. Given counts of issues across a batch of audio "
    "files, write a 2-3 sentence executive summary highlighting the most common problems "
    "and the single highest-impact corrective action."
)

_AGG_SCHEMA = {
    "type": "object",
    "additionalProperties": False,
    "properties": {"summary": {"type": "string"}},
    "required": ["summary"],
}


def _aggregate_summary(batch: BatchReport, *, use_llm: bool) -> str:
    clean = sum(1 for r in batch.reports if not r.issues)
    base = (
        f"Analysed {batch.file_count} file(s); {clean} clean. "
        f"Issue counts: {batch.issue_counts or 'none'}."
    )
    if not use_llm:
        return base
    try:
        data = complete_json(
            system=_AGG_SYSTEM,
            user=(
                f"Files analysed: {batch.file_count}. Clean files: {clean}. "
                f"Issue counts by type: {batch.issue_counts}."
            ),
            schema=_AGG_SCHEMA,
            schema_name="aggregate_summary",
        )
        return f"{data['summary']} (generated by {model_label()})"
    except LLMUnavailable:
        return base
